cmake_minimum_required(VERSION 3.30)
set(CMAKE_CXX_STANDARD 20)

project(test)
project(test2)
project(test3)
project(test4)


# add_executable(test
#     1.Fraction/Fraction.cpp
# )


# add_executable(test2
#     2.Matrix/Main.cpp
# )

# add_executable(test3
#     3.Money/Money.cpp
# )


add_executable(test4
        4.DDay/Day.cpp
        4.DDay/Main.cpp
)
